"""Fachada del módulo Box.

Los cogs importan desde acá y no directamente de ``database`` ni ``logic``,
igual que en los módulos Madrugue y SSF.
"""

from modules.box.combate import Plan, planificar, probabilidad_victoria
from modules.box.constants import (
    CALIDADES,
    EQUIPAMIENTO,
    MEJORAS,
    NIVEL_MAXIMO_EQUIPAMIENTO,
    NOMBRES_ACCIONES,
    NOMBRES_SPONSORS,
    SUMINISTROS,
    TEXTO_AYUDA,
    TIPOS_SUMINISTRO,
    TRATAMIENTOS,
)

from modules.box.database import (
    aceptar_desafio,
    asaltos_publicados,
    cerrar_combate,
    combate_en_curso,
    ESTADO_CANCELADO,
    ESTADO_TERMINADO,
    ESTADO_VIVO,
    fijar_canticos,
    latido_de,
    mensaje_de_asalto,
    obtener_canticos,
    obtener_combate_en_curso,
    obtener_combates_vivos,
    reclamar_asalto,
    registrar_mensaje_asalto,
    tiene_accion_activa,
    ultimos_combates,
    actualizar_mensaje_combate,
    admin_cancelar_accion,
    admin_completar_acciones_vencidas,
    admin_curar_usuario,
    admin_dar_sponsor,
    admin_finalizar_accion,
    admin_modificar_dinero,
    admin_modificar_experiencia,
    admin_modificar_probabilidad_lesion,
    admin_obtener_estadisticas_box,
    admin_obtener_historial_desafios,
    admin_obtener_info_usuario,
    admin_obtener_lesionados,
    admin_obtener_top_box,
    admin_quitar_sponsor,
    admin_reset_usuario,
    comprar_equipamiento_progresivo,
    comprar_mejora,
    comprar_tratamiento,
    completar_acciones_vencidas,
    crear_desafio,
    descansar,
    iniciar_accion,
    obtener_accion_activa,
    obtener_bonus_experiencia_sponsor,
    obtener_equipo,
    obtener_estado_box,
    obtener_estadisticas_box,
    obtener_nivel_mejora,
    obtener_saldo,
    obtener_sponsor_para_promocion,
    obtener_sponsors_activos,
    obtener_top_desafios,
    preparar_bot_para_desafio,
    procesar_pagos_sponsors,
    procesar_sponsors_medicos,
    reducir_probabilidad_lesion_inactivos,
    usar_suministro,
)

from modules.box.fighting import REGLAS_PELEA, planificar_pelea
from modules.box.logic import (
    Duracion,
    calidad_equipamiento,
    estadisticas_de_combate,
    es_nivel_maximo,
    formato_ratio,
    precio_equipamiento,
    precio_mejora,
    resolver_duracion,
    texto_horas,
)

from modules.box.narracion import (
    POOLS,
    apertura,
    cierre,
    dialogos,
    problemas_del_catalogo,
    recortar,
    veredicto,
)

from modules.box.sparring import REGLAS_SPARRING, planificar_sparring

__all__ = [
    # Combates en vivo
    "ESTADO_VIVO",
    "ESTADO_TERMINADO",
    "ESTADO_CANCELADO",
    "Plan",
    "REGLAS_PELEA",
    "REGLAS_SPARRING",
    "asaltos_publicados",
    "actualizar_mensaje_combate",
    "cerrar_combate",
    "combate_en_curso",
    "estadisticas_de_combate",
    "fijar_canticos",
    "latido_de",
    "obtener_canticos",
    "mensaje_de_asalto",
    "obtener_combate_en_curso",
    "obtener_combates_vivos",
    "planificar",
    "planificar_pelea",
    "planificar_sparring",
    "probabilidad_victoria",
    "reclamar_asalto",
    "registrar_mensaje_asalto",
    "tiene_accion_activa",
    "ultimos_combates",
    # Narración
    "POOLS",
    "apertura",
    "cierre",
    "dialogos",
    "problemas_del_catalogo",
    "recortar",
    "veredicto",
    # Constantes
    "CALIDADES",
    "EQUIPAMIENTO",
    "MEJORAS",
    "NIVEL_MAXIMO_EQUIPAMIENTO",
    "NOMBRES_ACCIONES",
    "NOMBRES_SPONSORS",
    "SUMINISTROS",
    "TEXTO_AYUDA",
    "TIPOS_SUMINISTRO",
    "TRATAMIENTOS",
    # Lógica pura
    "Duracion",
    "calidad_equipamiento",
    "es_nivel_maximo",
    "formato_ratio",
    "precio_equipamiento",
    "precio_mejora",
    "resolver_duracion",
    "texto_horas",
    # Persistencia
    "completar_acciones_vencidas",
    "crear_desafio",
    "aceptar_desafio",
    "comprar_mejora",
    "comprar_equipamiento_progresivo",
    "comprar_tratamiento",
    "obtener_nivel_mejora",
    "obtener_estadisticas_box",
    "obtener_saldo",
    "obtener_top_desafios",
    "descansar",
    "reducir_probabilidad_lesion_inactivos",
    "obtener_estado_box",
    "iniciar_accion",
    "obtener_accion_activa",
    "obtener_equipo",
    "obtener_sponsors_activos",
    "obtener_bonus_experiencia_sponsor",
    "obtener_sponsor_para_promocion",
    "preparar_bot_para_desafio",
    "procesar_pagos_sponsors",
    "procesar_sponsors_medicos",
    "usar_suministro",
    # Administración
    "admin_obtener_info_usuario",
    "admin_obtener_estadisticas_box",
    "admin_obtener_historial_desafios",
    "admin_obtener_lesionados",
    "admin_obtener_top_box",
    "admin_modificar_dinero",
    "admin_modificar_experiencia",
    "admin_curar_usuario",
    "admin_modificar_probabilidad_lesion",
    "admin_cancelar_accion",
    "admin_finalizar_accion",
    "admin_completar_acciones_vencidas",
    "admin_dar_sponsor",
    "admin_quitar_sponsor",
    "admin_reset_usuario",
]
